apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  -  port: {{ .Values.port }}
     targetPort: {{ .Values.targetPort }}
  type: {{ .Values.type }}